# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iis_code', models.CharField(default='mysite', max_length=32)),
                ('name', models.CharField(default='锅巴', max_length=20)),
                ('price', models.IntegerField(max_length=1000)),
                ('create_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
