# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('title', models.CharField(default='this is a party', max_length=50)),
                ('address', models.CharField(default='ShangHai', max_length=50)),
                ('is_off', models.BooleanField(default=False)),
                ('link', models.CharField(default='http://www.baidu.com', max_length=200)),
            ],
            options={
                'ordering': ('create_date',),
            },
        ),
    ]
