# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Lao', max_length=20)),
                ('weight', models.FloatField()),
                ('height_cm', models.IntegerField()),
            ],
        ),
    ]
